//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameNamespaceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.contoso.com", ConfigurationName="ServiceReference1.CalService")]
    public interface CalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.contoso.com/CalService/Add2", ReplyAction="http://www.contoso.com/CalService/Add2Response")]
        int Add2(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.contoso.com/CalService/Add2", ReplyAction="http://www.contoso.com/CalService/Add2Response")]
        System.Threading.Tasks.Task<int> Add2Async(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.contoso.com/CalService/Add3", ReplyAction="http://www.contoso.com/CalService/Add3Response")]
        int Add3(int x, int y, int z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.contoso.com/CalService/Add3", ReplyAction="http://www.contoso.com/CalService/Add3Response")]
        System.Threading.Tasks.Task<int> Add3Async(int x, int y, int z);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalServiceChannel : NameNamespaceClient.ServiceReference1.CalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalServiceClient : System.ServiceModel.ClientBase<NameNamespaceClient.ServiceReference1.CalService>, NameNamespaceClient.ServiceReference1.CalService {
        
        public CalServiceClient() {
        }
        
        public CalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add2(int x, int y) {
            return base.Channel.Add2(x, y);
        }
        
        public System.Threading.Tasks.Task<int> Add2Async(int x, int y) {
            return base.Channel.Add2Async(x, y);
        }
        
        public int Add3(int x, int y, int z) {
            return base.Channel.Add3(x, y, z);
        }
        
        public System.Threading.Tasks.Task<int> Add3Async(int x, int y, int z) {
            return base.Channel.Add3Async(x, y, z);
        }
    }
}
